name: PhpUnit
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: composer install
        run: composer install
      - name: composer test
        run: composer test
